spring:
  datasource:
    url: jdbc:mysql://localhost:3323/cinema?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 3245

logging:
  level:
    root: WARN
  file:
    name: app.log